# Generated by Django 4.1.5 on 2023-02-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmname', models.CharField(max_length=20)),
                ('filmdiscription', models.CharField(max_length=200)),
                ('filmnetwork', models.CharField(max_length=20)),
                ('filmdate', models.DateField()),
                ('filmadder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='myfilm.userr')),
            ],
        ),
    ]
